#
# Makefile for the VFD drivers.
#

# Each configuration option enables a list of files.

obj-$(CONFIG_VFD_ENABLE)		+= vfd.o
#obj-$(CONFIG_VFD_SM1628)		+= sm1628.o
#obj-$(CONFIG_VFD_CT1642)		+= ct1642.o
#obj-$(CONFIG_VFD_FD650)		+= fd650.o
obj-$(CONFIG_VFD_FD628SW)		+= fd628_drive.o

